title: Ken Nguyen
locale: "en"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Programming Blog
baseurl: ""
url: "https://kennguyen01.github.io/"
github_username:  kennguyen01

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-paginate
  - jekyll-sitemap
paginate: 5
paginate_path: /page:num/

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:categories/:title.html
      excerpt_separator: <!--more-->

# Google Analytics
google_analytics: UA-138983381-1

# Disqus Comments
discus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: nguyenkenv-com
